### ISSUE TITLE
Can't find image when creating DC

### ISSUE THREAD

**Issue by zimoony** [profitbricks/docker-machine-driver-profitbricks#12]
I try to execute the following command:
docker-machine create --driver profitbricks --profitbricks-cores "2" --profitbricks-disk-size "5" --profitbricks-location "de/fra" --profitbricks-username "<username>" --profitbricks-password "<pass>" <test-dev-server>

The error coming back is:
Running pre-create checks…
Error with pre-create check: "The image Ubuntu-16.04 de/fra does not exist.“

I also tried adding --profitbricks-disk-type "HDD" and --profitbricks-image "Ubuntu-16.04-LTS-server-2016-07-01" using the image name from the API (https://api.profitbricks.com/rest/v2/images/217f013b-3f4a-11e6-91c6-52540005ab80). It should be available in location "de/fra". It worked 1 week ago.

The error coming back is:
Running pre-create checks…
Error with pre-create check: "The image Ubuntu-16.04-LTS-server-2016-07-01 de/fra does not exist.“

**Comment by jasminSPC** [comment]
I just ran the following without any issues: 
```
$ docker-machine create -d profitbricks --profitbricks-disk-type "HDD" and --profitbricks-image "Ubuntu-16.04-LTS-server-2016-07-01" test
Invalid command line. Found extra arguments [--profitbricks-image Ubuntu-16.04-LTS-server-2016-07-01 test]
Jasmins-MacBook-Pro:~ jasmin$ docker-machine create -d profitbricks  --profitbricks-image Ubuntu-16.04-LTS-server-2016-07-01 test
Running pre-create checks...
Creating machine...
(test) Datacenter Created
(test) Server Created
(test) Volume Created
(test) Attached a volume to a server.
(test) LAN Created
(test) IP Block Reserved
(test) NIC created
(test) Updated server's boot image
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env test
$ docker-machine ls
NAME      ACTIVE   DRIVER         STATE     URL                          SWARM   DOCKER    ERRORS
default   -        virtualbox     Stopped                                        Unknown   
test      -        profitbricks   Running   tcp://158.222.103.155:2376           v1.11.2 
```
This is what I see in DCD:
![image](https://cloud.githubusercontent.com/assets/8327751/16626294/8b6a3c5e-43a8-11e6-8bb7-e0b5f86a2822.png)

I also ran this:

```
$ docker-machine create --driver profitbricks --profitbricks-cores 2 --profitbricks-disk-size 5 --profitbricks-location de/fra --profitbricks-image Ubuntu-16.04-LTS-server-2016-07-01  tst
Running pre-create checks...
Creating machine...
(tst) Datacenter Created
(tst) Server Created
(tst) Volume Created
(tst) Attached a volume to a server.
(tst) LAN Created
(tst) IP Block Reserved
(tst) NIC created
(tst) Updated server's boot image
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env tst
$ docker-machine ls
NAME      ACTIVE   DRIVER         STATE     URL                         SWARM   DOCKER    ERRORS
default   -        virtualbox     Stopped                                       Unknown   
tst       -        profitbricks   Running   tcp://157.97.111.135:2376           v1.11.2   
```
![image](https://cloud.githubusercontent.com/assets/8327751/16626353/c37e4ac2-43a8-11e6-8a23-b50a526b0d51.png)

We will keep an eye on this just to make sure this doesn't repeat.

**Comment by zimoony** [comment]
I solved the problem: 
The actual error was a special char ($) in my password which got expanded (vanished) when I setup everything with:
export PROFITBRICKS_PASSWORD="profitbricks_password"
Simply escaping the special char was the solution...

Now, the remaining issue is the misleading error message of the non-existing image at a certain location instead of proper "Auth failed"!

**Comment by jasminSPC** [comment]
That has been taken care of with v1.1.0
