### ISSUE TITLE
 docker-machine create is not able to create a machine

### ISSUE THREAD

**Issue by lbobka** [profitbricks/docker-machine-driver-profitbricks#13]
With the fresh installed profitbricks docker machine driver I´m not able to create a docker machine.
It always ends with the following error message:

Running pre-create checks...
Creating machine...
(ubuntu-test) Datacenter Created
(ubuntu-test) LAN Created
Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: index out of range
goroutine 28 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/docker/machine/libmachine/drivers/rpc.(*StandardStack).Stack(0xd68db8, 0x0, 0x0, 0x0)
        /root/work/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:23 +0x29
github.com/docker/machine/libmachine/drivers/rpc.trapPanic(0xc82010ba28)
        /root/work/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:129 +0x96
panic(0x85be20, 0xc82000a0b0)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/profitbricks/docker-machine-driver-profitbricks.(*Driver).Create(0xc8200b80c0, 0x0, 0x0)
        /root/work/src/github.com/profitbricks/docker-machine-driver-profitbricks/profitbricks.go:257 +0x1006
github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).Create(0xc8200b1b60, 0xd68db8, 0xd68db8, 0x0, 0x0)
        /root/work/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:140 +0x7c
reflect.Value.call(0x821000, 0x8d3b08, 0x13, 0x8eb978, 0x4, 0xc82010bed8, 0x3, 0x3, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x821000, 0x8d3b08, 0x13, 0xc82010bed8, 0x3, 0x3, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc820019b00, 0xc8200196c0, 0xc82000b7e0, 0xc820067180, 0xc8201282a0, 0x789380, 0xd68db8, 0x16, 0x789380, 0xd68db8, ...)
        /usr/local/go/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:477 +0x49d

**Comment by Larsen2285** [comment]
In the profitbricks DCD I can see that datacenter is created and also the server is connected to the internet and up and running, but I have the above mentioned error message while creating the machine.

**Comment by jasminSPC** [comment]
I believe I found the issue in question. Can you please try the latest binaries from https://github.com/profitbricks/docker-machine-driver-profitbricks/releases/tag/V1.1.1

Or if you are building the binaries yourself then do:
```
$go get -u github.com/profitbricks/docker-machine-driver-profitbricks
$cd $GOPATH/src/github.com/profitbricks/docker-machine-driver-profitbricks
$make install
```

Please let me know if this helps

**Comment by lbobka** [comment]
now it´s okay. thanks a lot

**Comment by jasminSPC** [comment]
Not a problem.

Thanks for the feed back
