### ISSUE TITLE
New Core Type Intel

### ISSUE THREAD

**Issue by lbobka** [profitbricks/docker-machine-driver-profitbricks#16]
Hi,

Profitbricks si offering now intel as an additional core type-
Is it possible to implement the new core type into this machine driver as well?

BR
Lars

**Comment by jasminSPC** [comment]
https://github.com/profitbricks/docker-machine-driver-profitbricks/releases/tag/v1.1.3

Cpu Family is available  as this parameter:

```
--profitbricks-cpu-family
```

Default value is **AMD_OPTERON**

**Comment by lbobka** [comment]
very cool!
Thanks

BR
Lars
