### ISSUE TITLE
datacenter paramter

### ISSUE THREAD

**Issue by lbobka** [profitbricks/docker-machine-driver-profitbricks#17]
Hi,

would it be possible to have a datacenterid parameter to have the possibility to provision servers in an existing datacenter?
Currently when creating a new server the driver will always create a new datacenter.

BR
Lars

**Comment by jasminSPC** [comment]
We are going to introduce that very soon. Stay tuned.

**Comment by jasminSPC** [comment]
We've added datacenter-id parameter in [v1.1.4](https://github.com/profitbricks/docker-machine-driver-profitbricks/releases/tag/v1.1.4)
The syntax:
```docker-machine create -d profitbricks --profitbricks-datacenter-id [dc_UUID] test```

If no Virtual DataCenter UUID is not provided docker-machine will create a machine in a new datacenter.
