### ISSUE TITLE
default ImagePassword

### ISSUE THREAD

**Issue by lbobka** [profitbricks/docker-machine-driver-profitbricks#18]
Hi,

which default password is used (ImagePassword) for created machines?

BR
Lars

**Comment by jasminSPC** [comment]
Currently no password is set. To log on to the machine you should use `docker-machine ssh [machine_name]`

**Comment by lbobka** [comment]
Now I tried to use ImagePassword in your profitbricks.go, because I saw you prepared the volume.go in your sdk part to set a password within VolumeProperties.

I added a few lines to your profitbricks.go:

type Driver struct {
   ....
   ImagePassword string
}

mcnflag.StringFlag{
                        EnvVar: "PROFITBRICKS_IMAGE_PASSWORD",
                        Name:   "profitbricks-imagepassword",
                        Usage:  "profitbricks image password",
},

d.ImagePassword = flags.String("profitbricks-imagepassword")

if d.ImagePassword == "" {
                d.ImagePassword = "PassWORD1234"
}

Properties: profitbricks.VolumeProperties{
                  Type:    d.DiskType,
                  Size:    d.DiskSize,
                  Name:    d.MachineName,
                  Image:   image,
                  ImagePassword:    d.ImagePassword,
                  SshKeys: []string{d.SSHKey},
},

But the server was not configured with the password provided in my profitbricks.go.

Could you please help?

BR
Lars

**Comment by jasminSPC** [comment]
How are you trying to access the machine?

p.s. If you can you can reach to me via skype (jasmin.gacic)

**Comment by jasminSPC** [comment]
Lars,

I added what you proposed, in the post above, to our code and built the plugin and I was able to both ssh into the box and also to login using the remote console in DCD with the password that was used to login.

Did you have any success with it?

**Comment by lbobka** [comment]
Hi Jasmin,

now I can access via DCD remote console my VMs.
Great!
Thanks for your help.

BR 
Lars
