### ISSUE TITLE
error while creating a new docker host with current version v1.1.4

### ISSUE THREAD

**Issue by lbobka** [profitbricks/docker-machine-driver-profitbricks#21]
Running pre-create checks...
Creating machine...
(check1) Datacenter Created
Error creating machine: Error in driver during machine creation: Error while creating a LAN {
  "httpStatus" : 404,
  "messages" : [ {
    "errorCode" : "309",
    "message" : "Resource does not exist"
  } ]
}
Rolling back...

I created the machine-driver as always:

go get -u github.com/profitbricks/docker-machine-driver-profitbricks
cd $GOPATH/src/github.com/profitbricks/docker-machine-driver-profitbricks
make install

BR
Lars

**Comment by jasminSPC** [comment]
Can you provide me with a command you used?

**Comment by jasminSPC** [comment]
I've found the issue and fixed it. Please go ahead and give it a try.

**Comment by lbobka** [comment]
thanks for the quick fix
