### ISSUE TITLE
JS error while opening profitbricks driver

### ISSUE THREAD

**Issue by hnategh** [profitbricks/docker-machine-driver-profitbricks#28]
Hi there,

I have added profitbricks driver to Rancher's drivers list, but when I try to open the profitbricks, the UI part does not show up and I get this js error on browser console. 
Uncaught TypeError: r.buildRenderNodes is not a function
    at Function.u.build (ember.prod.js:43508)

I found out that this happens because of ember version 2.11 and I changed the ember version to use 2.9.1 (ember:"2.9.1") instead of higher versions (ember:"^2.9.1"). Which seems to get rid of that JS error and being able to work with UI part of the driver. It would be nice solving this issue by whether to change the dependencies in bower.json to use absolute ember 2.9.1 or finding out why ember 2.11 is not compatible with your UI code.

I also saw another issue after creating a host via driver's UI, by giving a name (eg. 'node') and selecting quantity of 2, which I assumed according to the description written under the Name field I will have two nodes (hosts) called node1 and node2, but instead I ended up on profitbricks platform with two hosts which both were called node1. It would be very helpful to have created hosts as it is described in UI.

Thank you!
Hadi

**Comment by edevenport** [comment]
Hello @hnategh - Thank you for trying the Rancher UI driver and identifying the issue with the ember version. We appreciate your contribution of a proposed solution. This should be a relatively easy fix.

We will need to investigate the node quantity issue you describe. We will update the ticket as soon as these issues are addressed.

**Comment by alibazlamit** [comment]
Hello @hnategh I was trying to follow the steps you mentioned to investigate the issue with the nodes name, i was not able to encounter the problem you had, i have tried with/without providing a datacenterId and in each case the driver created two servers at ProfitBricks, could you maybe provide more information about the properties you provided, maybe the steps you followed to add the profitbricks driver to rancher ui?

Thanks

**Comment by alibazlamit** [comment]
@hnategh The issue with duplicate naming has been fixed in this [Release](https://github.com/profitbricks/ui-driver-profitbricks/releases/tag/v1.1.0), for now we have set the ember version to a fixed 2.9.1, ember changed the way the templates are being generated, we will continue to investigate the issue and possibly solve it but for now the 2.9.1 is good to use.

Please let us know if the release solved the issue for you and probably close this issue.

Thanks!

**Comment by hnategh** [comment]
@alibazlamit The problem is gone in the new release. Thank you very much for the fix!
