### ISSUE TITLE
Panic in .GetURL when changing password (unexpected EOF in docker-machine ls)

### ISSUE THREAD

**Issue by frederik** [profitbricks/docker-machine-driver-profitbricks#33]
I am seeing a _panic_ in docker-machine (0.12.02 and 0.13) when I change my profitbricks account password (which I used to create the docker-machines).

As soon as I change the password back I'm ok. I made sure to also try with the latest binaries from the release tab here on github.

I'm on MacOS 10.12.6
go version go1.8.3 darwin/amd64
Docker version 17.09.0-ce, build afdb6d4

```
frederik$ docker-machine --debug ls
Docker Machine Version:  0.13.0, build 9ba6da9
Found binary path at /Users/frederik/go/bin/docker-machine-driver-profitbricks
Launching plugin server for driver profitbricks
Plugin server listening at address 127.0.0.1:49973
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
timeout set to 10s
(my-machine-name3) Calling .GetURL
(my-machine-name3) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(my-machine-name3) DBG | [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x134621b]
(my-machine-name3) DBG | panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by jasmingacic** [comment]
@frederik I confirmed the problem. The problem is with error handling in the code. Except for the unclear message everything else should work fine. Of course you will have to change your environment variables in order for the plugin to work. 

We will work on this and will let you know as soon we have released a fix.

**Comment by jasmingacic** [comment]
The patch has been released:
https://github.com/profitbricks/docker-machine-driver-profitbricks/releases/tag/v1.3.3
 
Can you please validate the fix and close the issue.

**Comment by frederik** [comment]
Message with 1.3.3 now is 

```
Unauthorized. Either user name or password are incorrect.
```

After changing the password for each driver everything was back to normal 👍
