### ISSUE TITLE
Image Names / Aliases

### ISSUE THREAD

**Issue by Puller** [profitbricks/docker-machine-driver-profitbricks#34]
Unfortunately no Image name is accepted when using the latest docker-machine-driver:

> docker-machine create --driver profitbricks --profitbricks-location "de/fra" --profitbricks-image "Debian-8" test-machine-ben1
Running pre-create checks...
Error with pre-create check: "The image/alias  Debian-8 de/fra does not exist."
> 

Is there a special naming convention for image names? Where can I find a list of all image aliases?

**Comment by jasmingacic** [comment]
You could get the list of image aliases:
```
curl --include \
     --request GET \
     --user 'username@domain.tld:password' \
     https://api.profitbricks.com/cloudapi/v4/locations?depth=5
```
or you can use image ID which you can retrieve using the [CLI](https://github.com/profitbricks/profitbricks-cli).

**Comment by Puller** [comment]
Not working with the correct alias name either...

docker-machine create --driver profitbricks --profitbricks-location "de/fra" --profitbricks-image "debian:8" test-machine-ben1
Running pre-create checks...
Error with pre-create check: "The image/alias  debian:8 de/fra does not exist."

**Comment by jasmingacic** [comment]
@Puller I've just run the same command with my credentials and it worked fine:
```
jasmingacic$ docker-machine create --driver profitbricks --profitbricks-location "de/fra" --profitbricks-image "debian:8" test-machine-ben1
Running pre-create checks...
Creating machine...
(test-machine-ben1) <nil>
(test-machine-ben1) <nil>
(test-machine-ben1) Datacenter Created
(test-machine-ben1) LAN Created
(test-machine-ben1) Server Created
(test-machine-ben1) 81.173.114.202
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with debian...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env test-machine-ben1
```
![image](https://user-images.githubusercontent.com/8327751/33020238-cf32b160-cdfd-11e7-90dc-0332effe64cf.png)


Are you using the latest version of the plugin? Only versions 1.3.0+ supports image aliases

**Comment by edevenport** [comment]
Hello @Puller - I tested the same exact command line syntax as you and @jasmingacic. My Docker environment built successfully. Let me look into your question about the API differences.

In the meantime, could you try using an image UUID instead of the image alias?
