### ISSUE TITLE
NIC property "Dhcp" ignored when creating server

### ISSUE THREAD

**Issue by martingregoire** [profitbricks/docker-machine-driver-profitbricks#9]
I'm trying to extend the driver to let the user specify an option to disable DHCP on the NIC when a server is created.

Currently, when creating a server, DHCP is enabled by default. I tried to extend the `NicProperties` struct: https://github.com/profitbricks/docker-machine-driver-profitbricks/blob/master/profitbricks.go#L294
```go
	nicrequest := profitbricks.NicCreateRequest{
		NicProperties: profitbricks.NicProperties{
			Name: d.MachineName,
			Lan:  lan.Id,
			Ips:  []string{ip},
			Dhcp: false,		// added line
		},
```

According to the SDK this should work: https://github.com/profitbricks/profitbricks-sdk-go/blob/master/nic.go#L12

The server is created successfully, but when checking the server in ProfitBricks DCD, the DHCP option on the NIC is enabled.

Please advise if I'm doing something wrong.

**Comment by jasminSPC** [comment]
Sorry for the late reply. I took a look into the code changes you've added and everything looks legit. How are you creating Profitbricks machines?

Did you pass the correct flag like ** --profitbricks-lan-no-dhcp false**
Like for example 
```
docker-machine create --driver profitbricks --profitbricks-lan-no-dhcp false test-machine
```
